### ISSUE TITLE
Percentage

### ISSUE THREAD

**Issue by daviddelmonte** [JotaGalera/CalculatorUI#18]
Hi, beautiful control. What is your button sequence to calculate a percentage - specifically 50 + 10%?

Thanks

**Comment by JotaGalera** [comment]
Hi David, this is not possible at least for now.

First, you could use "%" in order to calculate 10%  and then add 50 to the result.
Currently, I am prioritizing the operations, but as soon as I finish the development, I´ll take a look at this.

Thanks for the suggestion

**Comment by daviddelmonte** [comment]
Thanks so much. If I come up with something, I'll let you know.

**Comment by JotaGalera** [comment]
Sure, your ideas are welcome! thank you so much!

**Comment by JotaGalera** [comment]
You can now tap in 50 + 10% and calculate the result 👍
